name: Lambda CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip tool
        run: sudo apt-get install zip

      - name: Zip Lambda function code
        run: zip -r code.zip TestLambdaFunction/*  # Ensure this is the correct path to your Lambda function code

      - name: Install AWS CLI (Update if preinstalled)
        run: |
          sudo apt-get install unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Update Lambda Function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'ap-south-1'
        run: |
          aws lambda update-function-code --function-name arn:aws:lambda:ap-south-1:030448577173:function:TestLambdaFunction --zip-file fileb://code.zip
